### ISSUE TITLE
Python version.

### ISSUE THREAD

**Issue by ariksu** [AndyGlx/FullControl-GCode-Designer#11]
Hello.

There is an info here and there that python version of full control gcode is on its way, but there is neither public repo nor any estimation. Can you share any plans with us? How could we help to bring this to life? 

Thank you for your great job!

**Comment by arifbalik** [comment]
Second this!

**Comment by AndyGlx** [comment]
Hey, thanks for asking! It's coming along, but am finalising the precise scope before releasing. So that it's clear and not confusing. Then, after release, I'll have a great big wishlist of things that I'd love people to help with, and no doubt people will have lots of other new ideas. But I'm still testing and honing for the next couple of months. Been a bit slow due to my lecturing job and having little free time over the last few months

**Comment by the-potato-church** [comment]
Is there any way to help out even now?

**Comment by javl** [comment]
@AndyGlx Any update on this? I'd love to give your tool a go, but rather jump into the python version (even if it is alpha) ;)

**Comment by AndyGlx** [comment]
Yep
www.tinyurl.com/wheresthedamnpythonversion
:)

First release will actually allow people to print without python at all. Then after making any necessary tweaks to things, the python version will be released. People will be able to share python designs with people who don't use python. I have a pretty strict personal deadline of September to get things public andnto have ironed out any creases, since I start uni lecturering from Oct.

**Comment by ElectricPotato** [comment]
I do not think this is coming out anytime soon, so I would suggest people use Grasshopper 3D to generate their 3D toolpaths
https://www.youtube.com/watch?v=Pi38EVP9ozM

**Comment by AndyGlx** [comment]
Python version is now available. Also free and open-source:

https://github.com/FullControlXYZ/fullcontrol
