### ISSUE TITLE
_xlfn issue with Excel 2010

### ISSUE THREAD

**Issue by RegEM** [AndyGlx/FullControl-GCode-Designer#8]
Cool program My Gleadall.

I'm running into some issues with Excel (2010). For example when I load the Lattice Demo sheet, some of links are created in a format that causes an error in my excel. The formula for cells L8 and for L9 are created as "_xlfn.SINGLE(Height)". 

When I try to generate the gcode, It errors on Feature 1.

I think I can manually recreate the links to the Height parameter. But I'm uncertain of all the implications. Perhaps I will just strip down the spreadsheet to have only one design per workbook.

From a little digging on google, this seems to be a known problem. See the following search result: https://techcommunity.microsoft.com/t5/excel/issue-xlfn-single-and-being-added-to-formulas-unsupported/m-p/1424697

fwiw, I see in Parameters.bas, a mention to "_xlfn"

Regards, Richard

**Comment by RegEM** [comment]
Never mind. I see you are redeveloping in Python. I will close this.

**Comment by AndyGlx** [comment]
Hi Richard, thanks for mentioning this. It's an issue that happens when files are used on different versions of Excel. For reference, you can definitely just recreate the links to the parameters. Also, there are some functions that change between versions of Excel (like CONCAT vs CONCATENATE), which can also just be recreated using the appropriate function name for whichever version of Excel is being used. Thanks for you interest and I hope you find it useful. Although I am working on a python version, I still think it's useful for people to be able to use this version without issues, so it's good to hear them! Thanks

**Comment by RegEM** [comment]
Thanks Andy. I'm often running into these types of issues. I prefer to use Excel 2003, lol. 
I'm finding your approach  and papers are  very inspirational.
